[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "cd 'Models/Assessment models'",
  "pip install --break-system-packages -r requirements_minimal.txt",
  "pip install --break-system-packages langchain==0.1.0 langchain-huggingface==0.3.1 langchain-core==0.1.0 pydantic==2.5.0 typing-extensions==4.8.0"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd 'Models/Assessment models' && python start.py" 