[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = [
  "cd 'Models/Assessment models'",
  "python -m pip install --user --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd 'Models/Assessment models' && python start.py" 