# Railway Configuration for Talento AI Backend
# This file configures the FastAPI backend deployment

[build]
builder = "nixpacks"

[deploy]
startCommand = "cd 'Models/Assessment models' && python start.py"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Environment variables
[deploy.envs]
PYTHON_VERSION = "3.11"

# Build environment
[build.envs]
NIXPACKS_PYTHON_VERSION = "3.11" 